#!/bin/bash

BASE=htgettoken-downloads
set -ex
cd "`dirname $0`"
rm -rf $BASE-*
BASE="$BASE-`sed -n 's/^%define downloads_version //p' htgettoken.spec`"
export MYPYTHONVERSION=3$(python3 -V|cut -d. -f2)
for pythonversion in 36 39; do
    (
    set -ex
    BASE=$BASE/python$pythonversion
    mkdir -p $BASE/.local
    if [ "$(pip3 --version|sed 's/[^ ]* \([^.]*\).*/\1/')" -lt 19 ]; then
        # newer pip3 needed for cryptography
        pip3 install -U --no-cache-dir --prefix $PWD/$BASE/.local pip
    fi
    PATH=$PWD/$BASE/.local/bin:$PATH
    export PYTHONPATH=`echo $PWD/$BASE/.local/lib/*/site-packages`
    PIPOPTS="download --no-cache-dir --python-version=$pythonversion -d $PWD/$BASE"
    # The --pyhon-version option requires either --only-binary=:all: or
    # --no-deps, and the former does not work on some packages so use
    # the latter when needed.  The disadvantage of --no-deps is that
    # it doesn't automatically pull in dependencies.
    pip3 $PIPOPTS --only-binary=:all: pyinstaller
    pip3 $PIPOPTS --no-deps m2crypto
    pip3 $PIPOPTS --only-binary=:all: pyOpenSSL
    pip3 $PIPOPTS --no-deps kerberos
    pip3 $PIPOPTS --only-binary=:all: paramiko
    pip3 $PIPOPTS --only-binary=:all: wheel
    if [ $MYPYTHONVERSION != $pythonversion ]; then
        rm -rf $BASE/.local
    fi
    )
done
tar czvf $BASE.tar.gz $BASE
rm -rf $BASE
