#!/bin/bash

BASE=htgettoken-downloads
set -ex
cd "`dirname $0`"
rm -rf $BASE-*
BASE="$BASE-`sed -n 's/^%define downloads_version //p' htgettoken.spec`"
mkdir $BASE
if [ "$(pip3 --version|sed 's/[^ ]* \([^.]*\).*/\1/')" -lt 19 ]; then
    # newer pip3 needed for cryptography
    pip3 install -U --no-cache-dir --prefix $PWD/$BASE/.local pip
fi
PATH=$PWD/$BASE/.local/bin:$PATH
export PYTHONPATH=`echo $PWD/$BASE/.local/lib/*/site-packages`
PIPOPTS="download --no-cache-dir -d $PWD/$BASE"
pip3 $PIPOPTS "pyinstaller<5.0"
pip3 $PIPOPTS m2crypto
pip3 $PIPOPTS pyOpenSSL
pip3 $PIPOPTS kerberos
pip3 $PIPOPTS paramiko
pip3 $PIPOPTS wheel
tar czvf $BASE.tar.gz $BASE
rm -rf $BASE
