#!/bin/bash

BASE=htgettoken-downloads
set -ex
cd "`dirname $0`"
rm -rf $BASE-*
BASE="$BASE-`sed -n 's/^%define downloads_version //p' htgettoken.spec`"
export MYPYTHONVERSION=3$(python3 -V|cut -d. -f2)
for pythonversion in 36 39; do
    (
    BASE=$BASE/python$pythonversion
    mkdir -p $BASE/.local
    if [ "$(pip3 --version|sed 's/[^ ]* \([^.]*\).*/\1/')" -lt 19 ]; then
        # newer pip3 needed for cryptography
        pip3 install -U --no-cache-dir --prefix $PWD/$BASE/.local pip
    fi
    PATH=$PWD/$BASE/.local/bin:$PATH
    export PYTHONPATH=`echo $PWD/$BASE/.local/lib/*/site-packages`
    PIPOPTS="download --no-cache-dir --python-version=$pythonversion --no-deps -d $PWD/$BASE"
    pip3 $PIPOPTS pyinstaller
    pip3 $PIPOPTS m2crypto
    pip3 $PIPOPTS pyOpenSSL
    pip3 $PIPOPTS kerberos
    pip3 $PIPOPTS paramiko
    pip3 $PIPOPTS wheel
    if [ $MYPTHONVERSION != $pythonversion ]; then
        rm -rf $BASE/.local
    fi
    )
done
tar czvf $BASE.tar.gz $BASE
rm -rf $BASE
